"""This module contains the list of error names and their custom message"""
from __future__ import annotations

from src.utils.error_message import ERROR_SOMETHING_WENT_WRONG


ERROR_MAPPING = {
    'AlreadyInitialized': 'node_is_already_initialized',
    'InvalidAddress': 'invalid_address',
    'InvalidAmount': 'invalid_amount',
    'InvalidAssetID': 'invalid_asset_id',
    'InvalidAttachments': 'invalid_attachment',
    'InvalidBackupPath': 'The backup path is invalid',
    'InvalidChannelID': 'invalid_channel_id',
    'InvalidMediaDigest': 'invalid_media_digest',
    'InvalidDetails': 'The details are invalid',
    'InvalidEstimationBlocks': 'invalid_estimation_blocks',
    'InvalidFeeRate': 'invalid_fee_rate',
    'InvalidName': 'invalid_name',
    'InvalidNodeIds': 'invalid_node_ids',
    'InvalidOnionData': 'invalid_onion_data',
    'InvalidPaymentSecret': 'invalid_payment_secret',
    'InvalidPassword': 'invalid_password',
    'InvalidPeerInfo': 'invalid_peer_info',
    'InvalidPrecision': 'invalid_precision',
    'InvalidPubkey': 'invalid_pubkey',
    'InvalidRecipientID': 'The recipient ID is invalid',
    'InvalidSwapString': 'invalid_swap_string',
    'InvalidTicker': 'invalid_ticker',
    'InvalidTlvType': 'invalid_tlv_type',
    'InvalidTransportEndpoint': 'invalid_transport_endpoint',
    'InvalidTransportEndpoints': 'invalid_transport_endpoints',
    'MediaFileEmpty': 'media_file_empty',
    'MediaFileNotProvided': 'media_file_not_provided',
    'FailedBitcoindConnection': 'failed_bitcoind_connection',
    'FailedBroadcast': 'failed_broadcast',
    'FailedPeerConnection': 'failed_peer_connection',
    'Indexer': 'indexer_error',
    'InsufficientAssets': 'insufficient_assets',
    'InsufficientCapacity': 'insufficient_capacity',
    'InsufficientFunds': 'insufficient_funds',
    'InvalidIndexer': 'invalid_indexer',
    'InvalidProxyEndpoint': 'invalid_proxy_endpoint',
    'InvalidProxyProtocol': 'invalid_proxy_protocol',
    'LockedNode': 'locked_node',
    'MaxFeeExceeded': 'max_fee_exceeded',
    'MinFeeNotMet': 'min_fee_not_met',
    'NetworkMismatch': 'network_mismatch',
    'NoAvailableUtxos': 'no_available_utxos',
    'NoRoute': 'no_route',
    'NotInitialized': 'not_initialized',
    'OpenChannelInProgress': 'open_channel_in_progress',
    'Proxy': 'proxy_error',
    'RecipientIDAlreadyUsed': 'recipient_id_already_used',
    'SyncNeeded': 'sync_needed',
    'TemporaryChannelIdAlreadyUsed': 'temporary_channel_id_already_used',
    'UnknownContractId': 'unknown_contract_id',
    'UnknownLNInvoice': 'unknown_ln_invoice',
    'UnknownTemporaryChannelId': 'unknown_temporary_channel_id',
    'UnlockedNode': 'unlocked_node',
    'UnsupportedLayer1': 'unsupported_layer_1',
    'UnsupportedTransportType': 'unsupported_transport_type',
    'Network': 'network_error',
    'JsonExtractorRejection': ERROR_SOMETHING_WENT_WRONG,
    'WrongPassword': 'wrong_password',
    'InvalidInvoice': 'invalid_invoice_error',
    'AlreadyUnlocked': 'already_unlocked',
    'OutputBelowDustLimit': 'output_below_dust_limit',
    'AllocationsAlreadyAvailable': 'allocations_already_available',
    'AnchorsRequired': 'anchors_required',
    'BatchTransferNotFound': 'batch_transfer_not_found',
    'CannotEstimateFees': 'cannot_estimate_fees',
    'CannotFailBatchTransfer': 'cannot_fail_batch_transfers',
    'ChangingState': 'changing_state',
    'ExpiredSwapOffer': 'expired_swap_offer',
    'FailedBdkSync': 'failed_bdk_sync',
    'FailedClosingChannel': 'failed_closing_channel',
    'FailedInvoiceCreation': 'failed_invoice_creation',
    'FailedIssuingAsset': 'failed_issuing_asset',
    'FailedKeysCreation': 'failed_keys_creation',
    'FailedMessageSigning': 'failed_messaging_signing',
    'FailedOpenChannel': 'failed_open_channel',
    'FailedPayment': 'failed_payment',
    'FailedPeerDisconnection': 'failed_peer_disconnection',
    'FailedSendingOnionMessage': 'failed_sending_onion_message',
    'IncompleteRGBInfo': 'incomplete_rgb_info',
    'InvalidAnnounceAddresses': 'invalid_announce_addresses',
    'InvalidAnnounceAlias': 'invalid_announce_alias',
    'InvalidSwap': 'invalid_swap',
    'IO': 'io_error',
    'Layer1Unsupported': 'layer_1_unsupported',
    'Unexpected': 'unexpected',
    'UnsupportedBackupVersion': 'unsupported_backup_version',
    'MissingSwapPaymentPreimage': 'missing_swap_payment_preimage',
    'NoValidTransportEndpoint': 'no_valid_transpoint_endpoint',
    # from caching
    'UnableToCacheInitialise': 'unable_to_cache_initialise',
    'CacheFetchFailed': 'cache_fetch_failed',
    'FailedToInvalidCache': 'failed_to_invalid_cache',
    'FailedToUpdateCache': 'failed_to_update_cache',
}
