"""This module contain info messages"""
from __future__ import annotations

INFO_COPY_MESSAGE = 'Text copied to clipboard'
INFO_LOG_SAVE_DESCRIPTION = 'Logs have been saved to {}'
INFO_CHANNEL_DELETED = 'Channel with pub key: {} has been deleted successfully'
INFO_FAUCET_ASSET_SENT = 'Asset "{}" has been sent successfully. It may take some time to appear in the wallet.'
INFO_NO_FILE = 'No file selected'
INFO_ASSET_ISSUED = 'Asset issued with asset id: {}'
INFO_ASSET_SENT = 'Asset sent successfully with Transaction Id: {}'
INFO_REFRESH_SUCCESSFULLY = 'Refresh Successfully'
INFO_BITCOIN_SENT = 'Transaction Id: {}'
INFO_LN_SERVER_STARTED = 'Ln node server started'
INFO_LN_NODE_STOPPED = 'Ln node stopped...'
INFO_LN_SERVER_ALREADY_RUNNING = 'Ln node already running'
INFO_DOWNLOAD_CANCELED = 'Download cancelled'
INFO_G_DRIVE_CONFIG_SUCCESS = 'Google drive configuration successful'
INFO_SENDING_ERROR_REPORT = 'Sending error report...'
INFO_FEE_RATE_SET = 'Fee Rate set: {}'
INFO_TITLE = 'Info'
INFO_CUSTOM_FEE_RATE = '{}: Please enter custom fee rate'
INFO_SET_FEE_RATE_SUCCESSFULLY = 'Fee rate set successfully'
INFO_GOOGLE_DRIVE = 'Google drive'
INFO_VALIDATION_OF_NODE_PASSWORD_AND_KEYRING_ACCESS = 'Please wait for validation of node password and keyring access'
INFO_BACKUP_COMPLETED = 'Backup completed! Your data is safe and secure.'
INFO_BACKUP_COMPLETED_KEYRING_LOCKED = 'Backup completed successfully! Please unlock the node to continue.'
INFO_FAUCET_NOT_AVAILABLE = 'Not yet available'
INFO_SET_EXPIRY_TIME_SUCCESSFULLY = 'Expiry time set successfully'
INFO_FAIL_TRANSFER_SUCCESSFULLY = 'The transfer has been marked as failed successfully.'
INFO_SET_ENDPOINT_SUCCESSFULLY = '{} set successfully.'
INFO_SET_MIN_CONFIRMATION_SUCCESSFULLY = 'Minimum confirmation set successfully'
INFO_ASSET_SENT_SUCCESSFULLY = 'Asset sent successfully'
INFO_RESTORE_COMPLETED = 'Restore process completed.'
INFO_STARTING_RLN_NODE = 'Starting RLN Node'
INFO_RESTARTING_RLN_NODE = 'Restarting RLN Node. Please do not close the app'
INFO_WALLET_RESET = 'Wallet has been reset successfully'
