name: Iris Wallet Desktop CI

on:
  push:
    tags:
      - "*" # Trigger workflow on any tag

jobs:
  setup:
    runs-on: ubuntu-22.04
    outputs:
      ln_node_artifact: ln_node_artifact
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1
          submodule-fetch-depth: 1

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          source "$HOME/.cargo/env"

      - name: Set up Python 3.12.3
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libxcb-cursor0 -y
          sudo apt-get install ruby-dev build-essential && sudo gem i fpm -f

      # - name: Clone rgb-lightning-node repository with submodules
      #   run: git clone https://github.com/RGB-Tools/rgb-lightning-node --recurse-submodules --shallow-submodules

      # - name: Build the rgb-lightning-node binary
      #   working-directory: rgb-lightning-node
      #   run: cargo install --locked --debug --path .

      # - name: Copy rgb-lightning-node binary to root directory
      #   run: |
      #     mkdir ln_node_binary
      #     cp rgb-lightning-node/target/debug/rgb-lightning-node ln_node_binary

      - name: Set environment variables from secrets and create config.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          AUTH_URI: ${{ secrets.AUTH_URI }}
          TOKEN_URI: ${{ secrets.TOKEN_URI }}
          AUTH_PROVIDER_CERT_URL: ${{ secrets.AUTH_PROVIDER_CERT_URL }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          EMAIL_ID: ${{ secrets.EMAIL_ID }}
          EMAIL_TOKEN: ${{ secrets.EMAIL_TOKEN }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          cd src/utils
          python generate_config.py

      - name: Install python dependencies
        run: |
          pip install poetry
          pip install pyinstaller
          poetry install

      - name: Compile QT resources
        run: |
          poetry run pyside6-rcc src/resources.qrc -o src/resources_rc.py

      - name: Upload environment as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ln_node_artifact
          path: |
            ln_node_binary
            src/resources_rc.py
            src/utils/config.py

  build-linux:
    runs-on: ubuntu-22.04
    needs: setup
    strategy:
      matrix:
        network: [regtest, testnet]
    steps:
      - name: Download environment artifact
        uses: actions/download-artifact@v4
        with:
          name: ln_node_artifact
          path: .

      - name: Install python dependencies
        run: |
          pip install poetry
          pip install pyinstaller
          poetry install

      - name: Create AppImage for ${{ matrix.network }}
        run: |
          sudo apt-get update && sudo apt-get install -y libfuse2
          poetry run build-iris-wallet --network=${{ matrix.network }} --distribution=appimage
          ARCH=$(uname -m)
          VERSION=$(grep '__version__' src/version.py | cut -d "'" -f 2)
          APPIMAGE_NAME="iriswallet-${VERSION}-${ARCH}.AppImage"
          echo "APPIMAGE_NAME=${APPIMAGE_NAME}" >> $GITHUB_ENV
          echo "Generated file: $APPIMAGE_NAME"
        shell: bash

      - name: Rename AppImage for ${{ matrix.network }}
        run: |
          ARCH=$(uname -m)
          VERSION=$(grep '__version__' src/version.py | cut -d "'" -f 2)
          NETWORK=${{ matrix.network }}
          ORIGINAL_NAME="iriswallet-${VERSION}-${ARCH}.AppImage"
          RENAMED_NAME="iriswallet-${NETWORK}-${VERSION}-${ARCH}.AppImage"
          mv ./uploads/${ORIGINAL_NAME} ./uploads/${RENAMED_NAME}
          echo "RENAMED_NAME=${RENAMED_NAME}" >> $GITHUB_ENV

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux_appimage_${{ matrix.network }}
          path: ${{ env.APPIMAGE_NAME }}

  upload-release:
    needs: build-linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Download Linux AppImage artifacts
        uses: actions/download-artifact@v4
        with:
          name: |
            linux_appimage_regtest
            linux_appimage_testnet
          path: ./uploads

      - name: Upload Release Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./uploads/${{ env.RENAMED_NAME }}
          asset_name: ${{ env.RENAMED_NAME }}
          asset_content_type: application/octet-stream
