name: Iris Wallet Desktop CI

on:
  push:
    tags:
      - '*' # Trigger this workflow on any tag push

jobs:
  build-iris-wallet-desktop:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true # Include submodules in the checkout
          fetch-depth: 1 # Fetch the latest commit only

      - name: Install Rust Programming Environment
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          source "$HOME/.cargo/env"

      - name: Set up Python 3.12.3 environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Install required system dependencies
        run: |
          sudo apt update
          sudo apt install libxcb-cursor0 -y # Required by the application
          sudo apt-get install ruby-dev build-essential -y && sudo gem i fpm -f
          sudo apt-get update && sudo apt-get install -y libfuse2 # Required for AppImage creation

      - name: Clone rgb-lightning-node repository with submodules
        run: git clone https://github.com/RGB-Tools/rgb-lightning-node --recurse-submodules --shallow-submodules

      - name: Build the rgb-lightning-node binary
        working-directory: rgb-lightning-node
        run: cargo install --locked --debug --path .

      - name: Copy rgb-lightning-node binary to root directory
        run: |
          mkdir ln_node_binary
          cp rgb-lightning-node/target/debug/rgb-lightning-node ln_node_binary

      - name: Set environment variables from GitHub Secrets and generate config.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          AUTH_URI: ${{ secrets.AUTH_URI }}
          TOKEN_URI: ${{ secrets.TOKEN_URI }}
          AUTH_PROVIDER_CERT_URL: ${{ secrets.AUTH_PROVIDER_CERT_URL }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SMTP_EMAIL_ID: ${{ secrets.SMTP_EMAIL_ID }}
          SMTP_EMAIL_TOKEN: ${{ secrets.SMTP_EMAIL_TOKEN }}
          SUPPORT_EMAIL: ${{ secrets.SUPPORT_EMAIL }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          cd src/utils
          python generate_config.py

      - name: Install Python dependencies
        run: |
          pip install poetry # Dependency management tool
          pip install pyinstaller # Required for building executable files
          poetry install # Install application dependencies

      - name: Compile QT resources
        run: |
          poetry run pyside6-rcc src/resources.qrc -o src/resources_rc.py

      - name: Create AppImage for Regtest network
        run: |
          ARCH=$(uname -m)
          VERSION=$(grep '__version__' src/version.py | cut -d "'" -f 2)
          poetry run build-iris-wallet --network=regtest --distribution=appimage
          REGTEST_APPIMAGE_NAME="iriswallet-${VERSION}-${ARCH}.AppImage"
          RENAME_REGTEST_APPIMAGE_NAME="iriswallet-regtest-${VERSION}-${ARCH}.AppImage"
          mv ${REGTEST_APPIMAGE_NAME} ${RENAME_REGTEST_APPIMAGE_NAME}
          echo "RENAME_REGTEST_APPIMAGE_NAME=${RENAME_REGTEST_APPIMAGE_NAME}" >> $GITHUB_ENV
          echo "Generated file: $RENAME_REGTEST_APPIMAGE_NAME"
        shell: bash

      - name: Upload Regtest AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux_appimage_regtest
          path: ${{ env.RENAME_REGTEST_APPIMAGE_NAME }}

      - name: Create AppImage for Testnet network
        run: |
          ARCH=$(uname -m)
          VERSION=$(grep '__version__' src/version.py | cut -d "'" -f 2)
          poetry run build-iris-wallet --network=testnet --distribution=appimage
          TESTNET_APPIMAGE_NAME="iriswallet-${VERSION}-${ARCH}.AppImage"
          RENAME_TESTNET_APPIMAGE_NAME="iriswallet-testnet-${VERSION}-${ARCH}.AppImage"
          mv ${TESTNET_APPIMAGE_NAME} ${RENAME_TESTNET_APPIMAGE_NAME}
          echo "RENAME_TESTNET_APPIMAGE_NAME=${RENAME_TESTNET_APPIMAGE_NAME}" >> $GITHUB_ENV
          echo "Generated file: $RENAME_TESTNET_APPIMAGE_NAME"
        shell: bash

      - name: Upload Testnet AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux_appimage_testnet
          path: ${{ env.RENAME_TESTNET_APPIMAGE_NAME }}

  release-artifacts:
    if: needs.build-iris-wallet-desktop.result == 'success'
    runs-on: ubuntu-latest
    needs: [build-iris-wallet-desktop]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Retrieve tag name
        run: |
          TAG_NAME=$(git describe --tags)
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          echo "Using tag: $TAG_NAME"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.TAG_NAME }}"
          release_name: "${{ env.TAG_NAME }}"
          draft: false
          prerelease: false

      - name: Read version and architecture information
        run: |
          VERSION=$(grep '__version__' src/version.py | cut -d "'" -f 2)
          ARCH=$(uname -m)
          TESTNET_APPIMAGE_NAME="iriswallet-testnet-${VERSION}-${ARCH}.AppImage"
          REGTEST_APPIMAGE_NAME="iriswallet-regtest-${VERSION}-${ARCH}.AppImage"
          echo "ARCH=${ARCH}" >> $GITHUB_ENV
          echo "TESTNET_APPIMAGE_NAME=${TESTNET_APPIMAGE_NAME}" >> $GITHUB_ENV
          echo "REGTEST_APPIMAGE_NAME=${REGTEST_APPIMAGE_NAME}" >> $GITHUB_ENV

      - name: Prepare uploads folder
        run: mkdir -p ./uploads

      - name: Download Testnet AppImage artifact
        uses: actions/download-artifact@v4
        with:
          name: linux_appimage_testnet
          path: ./uploads/testnet

      - name: Download Regtest AppImage artifact
        uses: actions/download-artifact@v4
        with:
          name: linux_appimage_regtest
          path: ./uploads/regtest

      - name: Upload Testnet AppImage to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./uploads/testnet/${{ env.TESTNET_APPIMAGE_NAME }}
          asset_name: iris-wallet-${{ env.TAG_NAME }}-testnet-${{env.ARCH}}.AppImage
          asset_content_type: application/octet-stream

      - name: Upload Regtest AppImage to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./uploads/regtest/${{ env.REGTEST_APPIMAGE_NAME }}
          asset_name: iris-wallet-${{ env.TAG_NAME }}-regtest-${{env.ARCH}}.AppImage
          asset_content_type: application/octet-stream

  cleanup-artifacts:
    if: always()
    runs-on: ubuntu-latest
    needs: [build-iris-wallet-desktop, release-artifacts]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete Artifacts from Workflow Run
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            linux_appimage_regtest
            linux_appimage_testnet
          failOnError: false
